# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: elife

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

# Tomcat
server:
  port: 7001      
  
  
# Logging
logging:
  file: elife.log
  level:
    root:  ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    com.goldenducks: DEBUG
    org.mongodb: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
